spring:
  application:
    name: spring-boot-rabbitmq-demo

  #消息队列配置
  rabbitmq:
    addresses: 192.168.1.238
    username: test
    password: test
    port: 5172
    virtual-host: test
    publisher-confirms: true

